### PR TITLE
chapter about hexagonal architecture

### LINKED ISSUE #50: Write about Hex Architecture
As shown in Figure 4.3 and Figure 4.4 , you used Hex Architecture to structure your code.

Please provide a Section about this architectural style.

May you add a Figure to explain the base idea behind ports & adapters as well as the domain model ? This would help to understand the file trees in Figure 4.3 and Figure 4.4.

### PR DESCRIPTION
**Pull request by TheMaxens**
I added a chapter 4.3 about the hexagonal architecture. I explained the different hexagons (domain, application, framwork) including some figures. 
I also mentioned the relationship with the folder structure.

fix #50

### CODE REVIEW

**Comment by philippabele** [comment]
- Please promote "Hex. Arc" to an own chapter. This should be placed between "Rem. dev" and "Implementation.
- Describe the Abbreviation SPI in Figure 4.5
- Remove the note about the existing VBA App in Chapter 5
- Add some notes about your opinion on Hex.Arc. Is this approach familiar to a student? What a pros and cons during or after implementation?

**Comment by TheMaxens** [comment]
@philippabele 
I have implemented the requested changes.

**Comment by philippabele** [comment]
@TheMaxens I could figure out, that the first three points have been fixed. May you could take a lookt at point 4 "pros and cons" in the conclusion ?

**Comment by TheMaxens** [comment]
@philippabele 
I have added a paragraph on this topic (see https://github.com/philippabele/ball-bearings-with-quarkus/pull/51/commits/ffa5b2ba8d74147e0439c7b8e3cd24d92861cca9#diff-408b6df09a73e49991b90e3219ae00399a5dc37c00ba01c8cb3ea601e568df12R375)
Is that enough?

**Comment by philippabele** [comment]
@TheMaxens it is okay. I was looking for your personal opinion in the conclusion, my mistake.

**Review by philippabele — APPROVED** [review]

**Pull request merged**
