### PR TITLE
Dev environment

### LINKED ISSUE #10: Set up remote development for Java project
The problems in the Pullrequest Basic Rest Api have shown how challenging setting up a development environment can be for different developers.

To avoid these problems for the next developer in this project, the development should be switched to inside a container.

The following links explain the concept for VS Code. 

https://code.visualstudio.com/docs/devcontainers/containers

I know two ways in VS Code to connect to a dev container. Via the Remote Explorer ( The SSH Way, which works also for VMs) and the Docker Extension ( Right Mouse Button > Attach VS Code to Container )

It looks like there is also an option for IntelliJ to develop in the Docker container via SSH.

https://www.jetbrains.com/remote-development/

https://www.jetbrains.com/help/idea/remote-development-starting-page.html#start_from_IDE

- [ ] Set up an development container

### PR DESCRIPTION
**Pull request by TheMaxens**
fix #10 

The procedure only works for VSCode. 

I updated the Readme with installation instructions. 

Unfortunately, I'm not able to sign my commits inside the container.

### CODE REVIEW

**Comment by philippabele** [comment]
Try the github command line to sign commits

https://cli.github.com/manual/gh_auth_login

**Comment by TheMaxens** [comment]
> Try the github command line to sign commits
> 
> https://cli.github.com/manual/gh_auth_login

The last commit "install github cli" was pushed after I executed `gh auth login` but there is still no signature.

**Comment by philippabele** [comment]
Sorry for.

There are three ways on GitHub

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

to sign.

How did you set up your local machine to sign?

**Comment by TheMaxens** [comment]
On my local machine I'm using GPG to sign my commits. 

I followed the [instructions](https://code.visualstudio.com/docs/devcontainers/containers#_sharing-gpg-keys) to share the GPG key. 
Inside my git config _user.SigningKey_ was set, but I receive an error when I try to commit (with signing option). 
I think my key isn't copied to the dev container.

**Comment by philippabele** [comment]
May it be a solution not share your key?

Is it possible within the container Telling Git about your GPG key the following way


https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key?platform=linux#telling-git-about-your-gpg-key-2

?

**Comment by philippabele** [comment]
You can copy your key into the container

https://askubuntu.com/questions/1069357/importing-gpg-key-in-ubuntubionic-docker-container#1069415

or you create an new one specific for this container

**Comment by TheMaxens** [comment]
Now it is working more or less.
I created a new key inside the dev container (known procedure).

When the container is running, execute this command `echo "export GPG_TTY=$(tty)" >> ~/.bashrc` once.

Currently, I'm only able to sign my commits via terminal. The git-integration in VSCode (Source Control on the left bar) doesn't really work.
`git add -A`
`git commit -S -m "message"` → enter passphrase
`git push`

**Comment by philippabele** [comment]
Is this behaviour really a problem of remote development in a container?

- [ ] Does your VS Code IDE show "remote connection with 123" in the lower left corner within the green field?

- [ ] Could you save your passphrase and try again?

- [ ] Could you try SSH verification?

**Comment by philippabele** [comment]
https://dev.to/devmount/signed-git-commits-in-vs-code-36do

**Comment by TheMaxens** [comment]
> Is this behaviour really a problem of remote development in a container?
> 
> * [ ]  Does your VS Code IDE show "remote connection with 123" in the lower left corner within the green field?
> * [ ]  Could you save your passphrase and try again?
> * [ ]  Could you try SSH verification?

Yes, I think it's a problem of remote development because in my local dev everything works fine.
https://stackoverflow.com/questions/63440623/no-gpg-passphrase-prompt-in-visual-studio-code-on-windows-10-for-signed-git-comm   

1) Yes, VSCode shows "Dev Container: Quarkus" in the lower left corner within the green field.

**Comment by philippabele** [comment]
Your proposed solution from stackoverflow sounds very interesting.

Did you tested it and could you prove the promised functionality from a container?


> Now it is working more or less. I created a new key inside the dev container (known procedure).
> 
> When the container is running, execute this command `echo "export GPG_TTY=$(tty)" >> ~/.bashrc` once.
> 
> Currently, I'm only able to sign my commits via terminal. The git-integration in VSCode (Source Control on the left bar) doesn't really work. `git add -A` `git commit -S -m "message"` → enter passphrase `git push`

How does the final solution looks like?

- [ ] Wrapping your lines of code in a shell script with one parameter named message ?

I would prefer this in order to keep going on with the actual project. Maybe there will come up another solution by chance.

Maybe, the hybrid way works aswell. You keep developing on your local machine and will perform the code review within the development container.

**Comment by TheMaxens** [comment]
I defined a shell script `commit.sh` which creates signed commits: 
`./commit.sh "commit message"`

The command `echo "export GPG_TTY=$(tty)" >> ~/.bashrc` is executed automatically when the container is created.

**Review by philippabele — APPROVED** [review]

**Pull request merged**
