### PR TITLE
docs: Latex documentation for git setup

### PR DESCRIPTION
**Pull request by TheMaxens**
I added chapter "Prerequisites" and "How to set up Git for remote development" to the docs.

Are they ok?

### CODE REVIEW

**Comment by philippabele** [comment]
Think of yourself. A student one year ago. Would you understand your own documentation ?

- Please describe step 13 in chapter 4. What is this command doing?

- Please add some screenshots in chapter 4.1

**Comment by TheMaxens** [comment]
> Think of yourself. A student one year ago. Would you understand your own documentation ?
> 
> * Please describe step 13 in chapter 4. What is this command doing?
> * Please add some screenshots in chapter 4.1

What do you mean with "A student one year ago"? 😄

**Comment by philippabele** [comment]
Doesn't matter :-)

I just wanted to express, that a comment like last but not least does not transport much content.

A simple and clear sentence about what your command do is enough in technical documents.

**Comment by TheMaxens** [comment]
I added:
- description of step 13 in chapter 4
- screenshots in chapter 4.1

**Review by philippabele — APPROVED** [review]

**Pull request merged**
